config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#home', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
     end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :purchases, only: [:create]
  end

  resources :purchases, only: [:show, :index]
  get 'my_products', to: 'products#my_products', as: :my_products

  # verb 'path', to: 'controller#action'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, :price, :category, presence: true
  has_one_attached :photo
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :purchases
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
    if params[:query].present?
      @show_banner = false
      sql_query = "name ILIKE :query OR details ILIKE :query OR category ILIKE :query"
      @products = Product.where(sql_query, query: "%#{params[:query]}%")
    else
      @show_banner = true
      @products = Product.all
    end
  end

  def list
    if user_signed_in?
      current_user.product
    else
      render :home, notice: 'Please, login first.'
    end
  end

  def my_products
    @products = current_user.products
  end

  def new
    @product = Product.new
  end

  def show; end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    if @product.user == current_user
      render :edit
    else
      redirect_to @product
    end
  end

  def update
    @product.update(product_params) if @product.user == current_user
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy if @product.user == current_user
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :details, :price, :category, :user_id, :photo)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = current_user.purchases
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def create
    @purchase = Purchase.new
    product = Product.find(params[:product_id])
    @purchase.product = product
    @purchase.user = current_user
    @purchase.value = product.price
    if @purchase.save!
      redirect_to purchase_path(@purchase)
    else
      render :home
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body style="background-color: #FBEEE9"; >
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper" style="margin-top: 62px">
      <%= yield %>
      <div class="push"></div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row row-cols-1 row-cols-md-3">
    <% @products.each do |product| %>
    <div class="col mb-4">
      <div class="card-index">
      <% if product.photo.attached? %>
        <%= cl_image_tag product.photo.key, class: 'card-img' %>
      <% else %>
        <%= cl_image_tag('vitor_k4t6bg.png', class: 'card-img') %>
      <% end %>

        <div class="card-body">
          <h6><%= link_to product.name, product_path(product) %></h6>
          <p>R$ <%= product.price %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :details %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary w-100 pd-3' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container-xl">
  <h2 class="p-3">Edit Product</h2>

  <%= render 'form', product: @product %>

  <%= link_to "Back to the list", products_path, class: 'btn btn-primary w-100 mt-2 mb-2' %>
</div>

app/views/products/index.html.erb
<% if @show_banner %>
  <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
          <div class="carousel-item active" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.8)), url(https://images.unsplash.com/photo-1456456496250-d5e7c0a9b44d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1651&q=80)">
              <div class="mask flex-center">
                  <div class="container">
                      <div class="row align-items-center" style="margin-top:60px">
                          <div class="col-md-8 col-12 order-md-1 order-2">
                              <h4 id="presentation">A <strong style="color:#9cebd5">Artsy</strong> conecta artesãos às pessoas que amam artesanato.</h4>
                              <p id="presentation2">Nosso trabalho é conectar ambas as partes, com <strong style="color:#9cebd5">taxas justas</strong> para os artesãos e <strong style="color:#9cebd5">preços justos </strong>para os consumidores.</p> <br>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="carousel-item" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.8)), url(https://images.unsplash.com/photo-1544443830-22675fff7986?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
              <div class="mask flex-center">
                  <div class="container">
                      <div class="row align-items-center" style="margin-top:60px">
                          <div class="col-md-8 col-12 order-md-1 order-2">
                              <h4>As <strong style="color:#9cebd5">canecas</strong> mais bonitas</h4>
                              <p>Aqui você vai encontrar as mais diversas canecas, em cores, tamanhos e materiais variados.</p> <br> <%= link_to 'COMPRAR AGORA', products_path(:query => 'mug') %>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div class="carousel-item" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.8)), url(https://images.unsplash.com/photo-1547056391-a8d5e1b05fc7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80)">
              <div class="mask flex-center">
                  <div class="container">
                      <div class="row align-items-center" style="margin-top:60px">
                          <div class="col-md-8 col-12 order-md-1 order-2">
                              <h4><strong style="color:#9cebd5">Suprimentos</strong> para os seus hobbies</h4>
                              <p>Encontre todos os materiais das suas marcas favoritas para o seu hobby, de linhas e costura a tinta.</p> <br> <%= link_to 'COMPRAR AGORA', products_path(:query => 'suprimentos') %>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div> <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
  </div>
<% end %>

<div class="card-grid" id="cardresult">

  <% @products.each do |product| %>
  <div class="newcard">

    <div class="product-img">
      <% if product.photo.attached? %>
        <%= cl_image_tag product.photo.key, class: "newcard-img" %>
      <% else %>
        <%= image_tag 'product-sample.png', class: "newcard-img" %>
      <% end %>
    </div>

    <div class="product-info">
      <div class="product-text">
        <h1><%= product.name.titleize %></h1>
        <h2>POR <%= product.user.email.split("@").first %></h2>
        <p><%= product.details %></p>
      </div>
      <div class="product-price">
        <p>R$ <span><%= product.price.to_i %>,00</span></p>
      </div>
      <div class="product-price-btn">
        <% if product.user == current_user %>
          <%= link_to "SUA VENDA", product_path(product), method: :get, class: "btn" %>
        <% else  %>
           <%= link_to "DETALHES", product_path(product), method: :get, class: "btn" %>
        <% end %>
      </div>
    </div>

  </div>
  <% end %>

</div>

app/views/products/my_products.html.erb
<div class="container">

  <div class="card-title">
  <h2 class="p-3" style="font-family: 'Bentham', serif; font-size: 34px; color: #474747;">Meus Produtos a Venda</h2>
</div>


  <table class="table">
    <thead>
      <tr style="font-family: 'Playfair Display', serif;">
        <th>Nome do Produto</th>
        <th>Preço</th>
        <th>Categoria</th>
        <th>Editar</th>
        <th>Deletar</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.name, product_path(product) %></td>
          <td>R$ <%= product.price.to_i %></td>
          <td><%= product.category %></td>
          <td><%= link_to "", edit_product_path(product), class: "far fa-edit"%></td>
          <td><%= link_to "",
                      product_path(product),
                      method: :delete,
                      data: { confirm: "Are you sure?" },
                      class: "far fa-trash-alt" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

 </div>

app/views/products/new.html.erb
<div class="container-xl">
  <h2 class="p-3">Create the product you want to sell</h2>

  <%= render 'form', product: @product %>

</div>

app/views/products/show.html.erb
<div class="container py-5">
  <div class="d-flex justify-content-center">
    <div class="">
       <% if @product.photo.attached? %>
        <%= cl_image_tag @product.photo.key, class: 'photo' %>
      <% else %>
        <%= image_tag 'product-sample.png', class: 'photo' %>
      <% end %>
    </div>
    <div class="p-5" id="card" style="background-color: white ">
      <h1><%= @product.name %></h1>
      <p id="price"><strong></strong>R$ <%= @product.price.to_i %>,00</p>
      <h5><strong>Description:</strong></h5>
      <p id="details"><strong></strong><%= @product.details %></p>

      <% if @product.user == current_user %>

      <h5><strong>This is your product. What do you want to do?</strong></h5>
      <div class="text-center">
        <%= link_to "Edit product", edit_product_path(@product), class: "btn btn-warning" %>
        <%= link_to "Delete product",
                  product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-danger" %>
      </div>
      <% else %>  <%= link_to "PURCHASE", product_purchases_path(@product), method: :post, class: "btn btn-primary btn-block mt-5", style: "bottom: 0"; %>
      <% end %>

    </div>
  </div>
</div>

app/views/purchases/index.html.erb
<div class="container" id="purchase">
  <h1 class="p-3">Minhas Compras</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Nome do Produto</th>
        <th>Preço</th>
        <th>Categoria</th>
        <th>Data da Compra</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @purchases.each do |purchase| %>
        <tr>
          <td><%= link_to purchase.product.name, purchase_path(purchase) %></td>
          <td>R$ <%= purchase.value.to_i %></td>
          <td><%= purchase.product.category %></td>
          <td><%= purchase.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/purchases/show.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col-md-8">
       <% if @purchase.product.photo.attached? %>
        <%= cl_image_tag @purchase.product.photo.key, class: 'card-img-top' %>
      <% else %>
        <%= image_tag 'product-sample.png', class: 'card-img-top' %>
      <% end %>
    </div>
    <div class="col-md-4" id="card" style="background-color: white ">
      <h2><%= @purchase.product.name %></h2>
      <p id="price"><strong></strong>R$ <%= @purchase.product.price %></p>
      <h5><strong>Description:</strong></h5>
      <p id="details"><strong></strong><%= @purchase.product.details %></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "Artsy.com", products_path, class: "navbar-brand", style: "color: #FBEEE9"; %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <form class="form-inline">
      <%= form_tag products_path(anchor: 'cardresult'), method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Procure por produtos" %>
        <%= submit_tag "Buscar", class: "btn btn-outline-info mx-2 my-sm-1" %>
      <% end %>
    </form>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", products_path, class: "nav-link", style: "color: #FBEEE9"; %>
        </li>
        <li class="nav-item">
          <%= link_to "Venda Algo!", new_product_path, class: "btn btn-info", style: "color: #79b0a1"; %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Minhas Compras", purchases_path, class: "dropdown-item" %>
            <%= link_to "Minhas Vendas", my_products_path, class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", style: "color: #FBEEE9"; %>
        </li>
      <% end %>
    </ul>
  </div>
</div>